### ISSUE TITLE
Can't auth

### ISSUE THREAD

**Issue by Skidamek** [mineblock11/Spoticraft#1]
video: https://streamable.com/5t5w39

log: https://mclo.gs/CeEiZW0

**Comment by IMB11** [comment]
Are you using a VPN? Using VPNs with spotify breaks OAuth2 and thus spoticraft isn't supported. This seems like a spotify problem, not a spoticraft one.

**Comment by Skidamek** [comment]
Would be cool if, but I don't use a VPN...

**Comment by IMB11** [comment]
Its a spotify issue sorry - theres absolutely nothing wrong with the mod.

**Comment by Skidamek** [comment]
sad, however interesting mod :)
have a good one
