### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Empezeeet** [mineblock11/Spoticraft#10]
I think it's my fault because I closed spotify login window at first launch.
Is there any way to open it again or just reset settings?

[crash-2023-06-21_18.16.18-client.txt](https://github.com/mineblock11/Spoticraft/files/11820268/crash-2023-06-21_18.16.18-client.txt)

**Comment by IMB11** [comment]
Yeah, this isn't reproducible. Delete the spotify config files and any files with "cred" or similarly named in the config folder to reset the mod to default.

**Comment by gggaming373** [comment]
> I think it's my fault because I closed spotify login window at first launch. Is there any way to open it again or just reset settings?
> 
> [crash-2023-06-21_18.16.18-client.txt](https://github.com/mineblock11/Spoticraft/files/11820268/crash-2023-06-21_18.16.18-client.txt)



> Yeah, this isn't reproducible. Delete the spotify config files and any files with "cred" or similarly named in the config folder to reset the mod to default.

i think that is what also happened with me no matter what the client is
how can i reset the mod?
