### ISSUE TITLE
Crash On Start

### ISSUE THREAD

**Issue by gggaming373** [mineblock11/Spoticraft#13]
When i tried for the first time it opened like a charm ( but i couldn't make that spotify connect thing cus i needed to close the game cus i 
needed to go to a place) but on the second try...
crash on start : here is the log file 

[latest.log](https://github.com/mineblock11/Spoticraft/files/12017631/latest.log)

**Comment by IMB11** [comment]
Spoticraft does not work with feather client. Please do not use feather client as it steals mods.
