### ISSUE TITLE
Spoticraft does not work with feather client. Please do not use feather client as it steals mods.

### ISSUE THREAD

**Issue by gggaming373** [mineblock11/Spoticraft#14]
Spoticraft does not work with feather client. Please do not use feather client as it steals mods.

_Originally posted by @mineblock11 in https://github.com/mineblock11/Spoticraft/issues/13#issuecomment-1631253939_

Why not just fix the mod so that it can work w feather?

**Comment by mineblock11** [comment]
Because feather steals mods. Please do not open another issue or you will be blocked.
