### ISSUE TITLE
How do I open or display the MiniGUI?

### ISSUE THREAD

**Issue by greymesa** [mineblock11/Spoticraft#16]
I was wondering how one would go about opening and showing the MiniGUI shown below while in-game.
![Screenshot](https://user-images.githubusercontent.com/93472213/192795951-033358cd-062d-4b8d-af1b-d4f10a99f4e4.png)

**Comment by esk33** [comment]
Press the hotkey (default is `O`)

**Comment by IMB11** [comment]
Hi, the playback toast is shown when the track changes, check your keybinds to see what the player screen is binded to.
