### ISSUE TITLE
not getting Spoticraft to run in minecraft java 1.20

### ISSUE THREAD

**Issue by Luna4886** [mineblock11/Spoticraft#17]
i have installed spoticraft for minecraft java 1.20 and i have done what spoticraft said to do but nothing has happened when i have done that the only thing i can do with the mide now that i have done all that is to open the spoticraft menu which there are no songs in Spoticraft so how do I fix it

**Comment by IMB11** [comment]
Make sure you downloaded the correct 1.20 version: https://modrinth.com/mod/spoticraft
