### ISSUE TITLE
Spoticraft changes Realms Parental Control Authentication

### ISSUE THREAD

**Issue by thmsmntro** [mineblock11/Spoticraft#18]
After Installing Spoticraft and successfully adding the API, I can no longer access realms as my account needs to be upgraded from a Mojang account to a Microsoft account. I have already made this migration over a year ago and was playing on Realms before the mod. Is there a way I can fix this on my end? I want to use the mod, but if I can't use it with Realms then I won't be continuing using it.

Thanks 😄

**Comment by IMB11** [comment]
Spoticraft has nothing to do with realms. Contact mojang.
