### ISSUE TITLE
Race condition loading album art on launch, crashing the game

### ISSUE THREAD

**Issue by Scotsguy** [mineblock11/Spoticraft#2]
Crash log:
https://paste.ee/p/LCsPg

This happens pretty consistently, perhaps 4/5 launches, and specifically when the toast displays on the title screen (you can even hear it)

**Comment by IMB11** [comment]
I wasn't able to replicate this on non-dev Minecraft but I was able to replicate it on Dev Minecraft, I can't find where this error is happening?

**Comment by IMB11** [comment]
Was fixed in https://github.com/11mods/Spoticraft/commit/fc2f21af39b68985ce4dc3146ed5f7cebd8d80b3
