### ISSUE TITLE
Setup window blank

### ISSUE THREAD

**Issue by al-eggs** [mineblock11/Spoticraft#5]
Hello! I'm using Spoticraft for the first time, but when the setup window appeared before the game launched, nothing on it loaded.
It's just a blank white box, and I can't seem to fix it or get past it.
Attached are images of the blank window and the mods/versions I'm using, if it helps.
![Screenshot 2022-10-05 at 8 18 37 PM](https://user-images.githubusercontent.com/95140552/194186515-18656f22-843f-46af-8322-e468992a3d62.png)
![Screenshot 2022-10-05 at 8 18 53 PM](https://user-images.githubusercontent.com/95140552/194186516-935c80d9-e2b9-4670-969d-73f2f37d647b.png)

**Comment by IMB11** [comment]
This seems to be a weirdly non reproducible issue on macos. 

You can trigger setup manually by going to `http://localhost:23435/setup` in a web browser.

Do not close the webview until it says so in the browser.
