### ISSUE TITLE
No Internet connection

### ISSUE THREAD

**Issue by HotKiller1337** [mineblock11/Spoticraft#8]
![WARUM](https://user-images.githubusercontent.com/96347017/223284154-e200c873-5a89-45ae-a17b-292e326725a1.png)
I dont know why is does that say but i have clearly an internet connection i tried wiht Hotspot from my phone and it didnt work and i wont give up Im also using the newest version @mineblock11

**Comment by IMB11** [comment]
The internet check pings google.com - is google blocked by your ISP or something?

**Comment by HotKiller1337** [comment]
Google is not blocked by my ISP and i let it start with google in the background but still the same problem can it be because i use linux?

**Comment by IMB11** [comment]
I can't reproduce this issue sorry - i've tried four times on my ubuntu laptop.
